### ISSUE TITLE
Not working at all with global PHPUnit

### ISSUE THREAD

**Issue by Soullivaneuh** [matthiasnoback/SymfonyDependencyInjectionTest#48]
If we run tests based on your library with a global phpunit binary, it fails. But it works with phpunit as a project dependency.

See more details here: https://github.com/sonata-project/SonataAdminSearchBundle/pull/16#issuecomment-113506010

And the related test case: https://github.com/sonata-project/SonataAdminSearchBundle/blob/72b0a5c5202ae8da33b5c1ea7936afde8e117e1d/Tests/DependencyInjection/Compiler/DatagridBuilderInjectionCompilerPassTest.php

We can't figure out why.

Maybe do you have an explanation?

Thanks.

**Comment by greg0ire** [comment]
I found the explanation, this can be closed.
For the record, the phpunit binary starts like this : 

```
foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        define('PHPUNIT_COMPOSER_INSTALL', $file);
        break;
    }
}
```

When the system's phpunit is used, the autoload file is (in my case) `~/.composer/vendor/phpunit/phpunit/../../autoload.php`

This might be a bug in phpunit. It should look in the current working directory first, I think.

**Comment by Soullivaneuh** [comment]
@greg0ire I'll keep it open unless a solution is found, thanks.

**Comment by greg0ire** [comment]
You should close it, because it has nothing to do with this package. The problem probably arises at the very first step : there is no dot in the output, signalling that a test was successful. I think if you remove this test, it will fail on another test, as soon as php tries to autoload something. Since it has the wrong autoloader, it can't autoload anything that isn't also require globally. It probably won't be able to load any class from the library under test, for instance.

**Comment by Soullivaneuh** [comment]
Thanks @greg0ire.
