### ISSUE TITLE
assertContainerBuilderHasResource

### ISSUE THREAD

**Issue by hacfi** [matthiasnoback/SymfonyDependencyInjectionTest#62]
Hey @matthiasnoback & other GitHubbers,
writing some tests last night I was thinking about testing dependency injection extensions and all the `assertContainerBuilderHasService`, `assertContainerBuilderHasParameter` etc assertations only make sense if they were actually added by the extension and not loaded via a yml/xml file. If my `load` method only loads a yml/xml file the only assertation that makes sense to me is that I check if that file was added as a file resource (and therefore loaded). So I was wondering if you think it makes sense to add a `assertContainerBuilderHasResource` assertion? For example
`$this->assertContainerBuilderHasResource('src/AppBundle/Resources/config/services.xml');`

**Comment by matthiasnoback** [comment]
Well, I don't think that would be good thing to add, since the container having a resource is basically a side-effect of loading a file (it's in fact only used for checking the freshness of the cache).
Anyway, for quite some time now I haven't been sure about this library anyway. I feel like it's much more useful to test your bundle when it actually cooperates with the bundle system. So just create a test kernel and load the bundles you want to test.

**Comment by matthiasnoback** [comment]
Closing this, I assume it's not relevant (anymore) :) Thanks anyway.
